# Large VCS / IDE / OS metadata
.git
.gitmodules
.github
.husky
.idea
.DS_Store

# Build artifacts and caches
target
node_modules
dist
build
.parcel-cache

# Files not needed in the WebUI image
*.md
*.dockerignore
.env
.nvmrc
Dockerfile*
LICENSE
Cargo.*
rustfmt.toml
secutils.toml

# Directories not needed in the WebUI image
dev
/src
/assets
/migrations
/.sqlx
/e2e
/components/secutils-docs
/components/secutils-jwt-tools
/components/retrack
