# syntax=docker/dockerfile:1

FROM --platform=$BUILDPLATFORM node:24-alpine3.24@sha256:a0b9bf06e4e6193cf7a0f58816cc935ff8c2a908f81e6f1a95432d679c54fbfd AS builder
WORKDIR /app

# See, https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#node-gyp-alpine
RUN apk add --no-cache python3 make g++

# Copy `package.json` file from the component, to just install dependencies.
COPY ["components/secutils-webui/*.json", "./"]
RUN set -x && npm ci

# Now copy the rest of the component files and build it.
COPY ["components/secutils-webui", "./"]
RUN set -x && npm run build

FROM nginxinc/nginx-unprivileged:alpine3.24-slim@sha256:d9fa63891743a11eb56ca1b22d8cc227491df183ca3da2cf1bf2c6e010bf19a5
COPY --from=builder ["/app/dist/", "/usr/share/nginx/html/"]
COPY ["components/secutils-webui/config/nginx.conf", "/etc/nginx/conf.d/default.conf"]
