# Paths that should be ignored by all Docker images
*.md
.DS_Store
.env
.github
.husky
.idea
.nvmrc
Dockerfile
LICENSE
dev
dist
node_modules
rustfmt.toml
secutils.toml
target

# Path that should be ignored by WebUI Docker image
/src
/components/secutils-webui
/components/secutils-jwt-tools
