server {
    listen       8080;
    listen  [::]:8080;
    server_name  localhost;

    gzip_static on;
    gzip on;
    gzip_types text/plain text/html text/css application/javascript text/xml application/xml image/svg+xml;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        try_files $uri $uri/index.html $uri/ $uri.html =404;
        error_page 404 /docs/404.html;
    }

    location ~* \.(?:jpg|jpeg|png|webp|woff2|svg|svgz|css|js)$ {
        root   /usr/share/nginx/html;
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
        add_header Vary "Accept-Encoding";
    }

    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self'; img-src 'self' data: secutils.dev github.com avatars.githubusercontent.com";
}
