### List private keys.
GET {{host}}/api/utils/certificates/private_keys
Authorization: {{api-credentials}}
Accept: application/json

### Get private key by ID
GET {{host}}/api/utils/certificates/private_keys/018b7720-7d12-7cd1-9fde-81a4b109199f
Authorization: {{api-credentials}}
Accept: application/json

### Create private key (RSA, without passphrase).
POST {{host}}/api/utils/certificates/private_keys
Authorization: {{api-credentials}}
Accept: application/json
Content-Type: application/json

{
  "keyName": "pk",
  "alg": { "keyType": "rsa", "keySize": "1024" }
}

### Update private key.
PUT {{host}}/api/utils/certificates/private_keys/018b77c3-a901-7272-a5d3-41ca17d163c9
Authorization: {{api-credentials}}
Accept: application/json
Content-Type: application/json

{
  "keyName": "pk-new-name",
  "newPassphrase": "123"
}

### Delete private key.
DELETE {{host}}/api/utils/certificates/private_keys/018b7720-7d12-7cd1-9fde-81a4b109199f
Authorization: {{api-credentials}}

### Export private key.
POST {{host}}/api/utils/certificates/private_keys/018b77c3-a901-7272-a5d3-41ca17d163c9/export
Authorization: {{api-credentials}}
Accept: application/json
Content-Type: application/json

{
  "format": "pem",
  "passphrase": "123"
}
