### Create private key (RSA, without passphrase).
POST {{host}}/api/utils/action
Authorization: {{api-credentials}}
Accept: application/json
Content-Type: application/json

{
  "action": {
    "type": "certificates",
    "value": {
      "type": "createPrivateKey",
      "value": { "keyName": "pk", "alg": { "keyType": "rsa", "keySize": "1024" } }
    }
  }
}

### Create private key (ed25519, with passphrase).
POST {{host}}/api/utils/action
Authorization: {{api-credentials}}
Accept: application/json
Content-Type: application/json

{
  "action": {
    "type": "certificates",
    "value": {
      "type": "createPrivateKey",
      "value": { "keyName": "pk-ed25519", "alg": { "keyType": "ed25519" }, "passphrase": "123456" }
    }
  }
}

###

### Export private key.
POST {{host}}/api/utils/action
Authorization: {{api-credentials}}
Accept: application/json
Content-Type: application/json

{
  "action": {
    "type": "certificates",
    "value": {
      "type": "exportPrivateKey",
      "value": { "keyId": "018b4a1b-92d3-739d-a4dd-683d9eb47ce9", "format": "pem", "passphrase": "123456" }
    }
  }
}

### Get private keys.
POST {{host}}/api/utils/action
Authorization: {{api-credentials}}
Accept: application/json
Content-Type: application/json

{
  "action": {
    "type": "certificates",
    "value": { "type": "getPrivateKeys" }
  }
}
