### Track web page resources
POST {{host}}/api/utils/action
Authorization: {{api-credentials}}
Accept: application/json
Content-Type: application/json

{
  "action": {
    "type": "webScraping",
    "value": {
      "type": "fetchWebPageResources",
      "value": { "trackerName": "test", "refresh": false }
    }
  }
}

