### Test webhook.
GET {{host}}/api/webhooks/ar/323c9f98b2e86fd9/redirect
Accept: application/json
Content-Type: application/json

{
  "action": {
    "type":  "certificates",
    "value": { "type": "generateRsaKeyPair" }
  }
}
