### Test webhook (path).
GET {{host}}/api/webhooks/su/a
Accept: application/json
Content-Type: application/json

### Test webhook (subdomain).
GET {{host}}/api/webhooks
Accept: application/json
Content-Type: application/json
X-Forwarded-Host: su.{{host}}
X-Replaced-Path: /a
