### Get data
GET {{host}}/api/user/data?namespace=userSettings
Accept: application/json
Authorization: {{api-credentials}}

### Get utils data
GET {{host}}/api/user/data?namespace=webPageResourcesTrackers
Accept: application/json
Authorization: {{api-credentials}}
