### Update data
POST {{host}}/api/user/data?namespace=userSettings
Accept: application/json
Content-Type: application/json
Authorization: {{api-credentials}}

{
  "dataValue": "{ \"certificates.doNotShowSelfSignedWarning\": true }"
}

### Remove data
POST {{host}}/api/user/data?namespace=userSettings
Accept: application/json
Content-Type: application/json
Authorization: {{api-credentials}}

{
  "dataValue": "{ \"certificates.doNotShowSelfSignedWarning\": null }"
}

### Save utils data
POST {{host}}/api/user/data?namespace=webPageResourcesTrackers
Accept: application/json
Content-Type: application/json
Authorization: {{api-credentials}}

{
  "dataValue":"{\"test\":{\"n\":\"test\",\"u\":\"https://secutils.dev\"}}"
}
