### Update data
POST {{host}}/api/user/data?namespace=userSettings
Accept: application/json
Content-Type: application/json
Authorization: {{api-credentials}}

{
  "dataValue": "{ \"certificates.doNotShowSelfSignedWarning\": true }"
}

### Remove data
POST {{host}}/api/user/data?namespace=userSettings
Accept: application/json
Content-Type: application/json
Authorization: {{api-credentials}}

{
  "dataValue": "{ \"certificates.doNotShowSelfSignedWarning\": null }"
}
