### Create web page resources tracker
POST {{host}}/api/utils/web_scraping/content
Authorization: {{api-credentials}}
Accept: application/json
Content-Type: application/json

{
  "name": "HackerNewsDemo",
  "url": "https://news.ycombinator.com/",
  "settings": {
    "revisions": 1,
    "delay": 5000,
    "enableNotifications": true
  }
}
