### Get content security policy
GET {{host}}/api/web_security/csp/{{policy_id}}
Authorization: {{api-credentials}}
Accept: application/json

### Share content security policy
POST {{host}}/api/web_security/csp/{{policy_id}}/_share
Authorization: {{api-credentials}}
Accept: application/json
Content-Type: application/json

### Unshare content security policy
POST {{host}}/api/web_security/csp/{{policy_id}}/_unshare
Authorization: {{api-credentials}}
Accept: application/json
Content-Type: application/json

### Import content security policy (text)
POST {{host}}/api/web_security/csp
Authorization: {{api-credentials}}
Accept: application/json
Content-Type: application/json

{
  "name": "csp-import-text",
  "content": {
    "type": "serialized",
    "value": "default-src 'wasm-unsafe-eval' 'unsafe-inline' 'strict-dynamic'; script-src 'unsafe-hashes'; style-src 'strict-dynamic'; img-src 'strict-dynamic'; font-src 'unsafe-hashes'; child-src 'unsafe-inline'; connect-src 'none'; frame-src 'self'; manifest-src 'self'; media-src 'report-sample'; object-src 'unsafe-inline'; script-src-elem 'unsafe-eval' 'wasm-unsafe-eval' 'unsafe-hashes' 'unsafe-inline'; script-src-attr 'wasm-unsafe-eval' 'unsafe-inline'; style-src-elem 'unsafe-hashes' 'unsafe-allow-redirects' 'wasm-unsafe-eval'; style-src-attr 'unsafe-hashes'; worker-src 'report-sample'; base-uri 'report-sample'; sandbox allow-pointer-lock allow-presentation allow-forms allow-popups allow-popups-to-escape-sandbox allow-modals allow-orientation-lock; form-action 'unsafe-allow-redirects' 'unsafe-inline' 'wasm-unsafe-eval'; frame-ancestors 'none'; report-uri https://secutils.dev/report"
  }
}

### Import content security policy (url, enforcing header)
POST {{host}}/api/web_security/csp
Authorization: {{api-credentials}}
Accept: application/json
Content-Type: application/json

{
  "name": "csp-import-url-enforcing-header",
  "content": {
    "type": "remote",
    "value": {
      "url": "https://github.com",
      "followRedirects": true,
      "source": "enforcingHeader"
    }
  }
}

### Import content security policy (url, multiple enforcing headers)
POST {{host}}/api/web_security/csp
Authorization: {{api-credentials}}
Accept: application/json
Content-Type: application/json

{
  "name": "csp-import-url-n-enforcing-headers",
  "content": {
    "type": "remote",
    "value": {
      "url": "https://accounts.google.com/ServiceLogin",
      "followRedirects": true,
      "source": "enforcingHeader"
    }
  }
}

### Import content security policy (url, reporting-only header)
POST {{host}}/api/web_security/csp
Authorization: {{api-credentials}}
Accept: application/json
Content-Type: application/json

{
  "name": "csp-import-url-report-only-header",
  "content": {
    "type": "remote",
    "value": {
      "url": "https://youtube.com",
      "followRedirects": true,
      "source": "reportOnlyHeader"
    }
  }
}

### Serialize content security policy
POST {{host}}/api/web_security/csp/{{policy_id}}/_serialize
Authorization: {{api-credentials}}
Accept: application/json
Content-Type: application/json

{
  "source": "enforcingHeader"
}
