### Test webhook (path).
GET {{host}}/api/webhooks/su/a
Accept: application/json
Content-Type: application/json

### Test webhook (subdomain).
GET {{host}}/api/webhooks
Accept: application/json
Content-Type: application/json
X-Forwarded-Host: su.{{host}}
X-Replaced-Path: /a

### Clear responder requests history.
POST {{host}}/api/utils/webhooks/responders/018cb666-e66c-755c-8d1e-7ff6cacb8641/clear
Authorization: {{api-credentials}}
Accept: application/json

### Get all responders.
GET {{host}}/api/utils/webhooks/responders
Cookie: {{cookie-credentials}}
Accept: application/json

### Get all responders stats.
GET {{host}}/api/utils/webhooks/responders/stats
Cookie: {{cookie-credentials}}
Accept: application/json




