#!/bin/sh

set -eu

if ! make webui-test
then
    echo "There are some WebUI test issues."
    exit 1
fi

if ! cargo sqlx prepare --check
then
    echo "Database schema snapshot should be updated."
    echo "Run `cargo sqlx prepare` first."
    exit 1
fi

if ! cargo +nightly fmt --all -- --check
then
    echo "There are some code style issues."
    echo "Run `cargo fmt` first."
    exit 1
fi

if ! cargo clippy --all --all-targets -- -D warnings
then
    echo "There are some Clippy issues."
    exit 1
fi

if ! cargo test
then
    echo "There are some API test issues."
    exit 1
fi

exit 0
